#!/usr/bin/env python2

import os
import sys
import ConfigParser
import Process


def log(message, username):
    print(message)
    path = "/home/{}/".format(username)
    if not os.path.isdir("/home/{}/".format(username)):
        path = "/root/"
    path += "retrovidsaver-ERROR.log"
    with open(path, 'a+') as f:
        f.write(message + "\n")
        f.flush()

if __name__ == "__main__":
    # Load config settings
    CONFIGPATH = "/etc/retrovidsaver.cfg"
    if not os.path.isfile(CONFIGPATH):
        username = "root"
        timer = 10
        message = "{} does not exist. Assuming defaults.".format(CONFIGPATH)
        log(message, username)
    else:
        config = ConfigParser.ConfigParser()
        config.read(CONFIGPATH)

        username = config.get("UserSettings", "username")
        timer = config.getint("UserSettings", "timer")

    # Exit if an instance of xautolock is already running
    ProcessName = "xautolock"
    if Process.isRunning(ProcessName):
        message = "{} already running".format(ProcessName)
        log(message, username)
        sys.exit(1)
    else:
        import time
        curtime = time.ctime()
        message = "retrovidsaver-start ran at {}".format(curtime)
        log(message, username)
        cmd = 'xautolock -time {} -locker "sudo /usr/local/bin/retrovidsaver/screensaver.py"'.format(timer)
        os.system(cmd)
